use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let project_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("host/ should sit under the project root")
        .to_path_buf();
    let manifest_path = project_root.join("tacit.toml");
    let lock_path = project_root.join("tacit.lock");
    let package_hash =
        package_hash_from_lock(&lock_path).expect("read package hash from tacit.lock");
    let run_hash = export_hash_from_manifest(&manifest_path, "run")
        .expect("read [exports].run from tacit.toml");
    let package_prefix = hash_prefix(&package_hash);
    let run_prefix = hash_prefix(&run_hash);
    let derived = project_root
        .join(".tacit")
        .join("derived")
        .join(format!("package-{package_hash}"))
        .join("host");

    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", lock_path.display());
    println!("cargo:rerun-if-changed={}", derived.display());
    rerun_if_sources_change(&project_root.join("src"));

    let (lib_dir, lib_basename, bindings_path) = find_host_artifacts(&derived).expect(
        "no Tacit host artifacts for the locked package — run `tacit interface . --emit-library`",
    );

    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    println!("cargo:rustc-link-lib=static={}", lib_basename);

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let staged = out_dir.join("tacit_host.rs");
    let shim = out_dir.join("tacit_host_shim.rs");
    let raw = fs::read_to_string(&bindings_path).expect("read generated bindings");
    let run_symbol = format!("tacit_p_{package_prefix}_e_{run_prefix}");
    if !raw.contains(&format!("pub fn {run_symbol}(")) {
        panic!(
            "generated bindings do not contain [exports].run symbol {run_symbol}; run `tacit interface . --emit-library`"
        );
    }
    let stripped: String = raw
        .lines()
        .filter(|line| !line.trim_start().starts_with("#!["))
        .collect::<Vec<_>>()
        .join("\n");
    fs::write(&staged, stripped).expect("write staged bindings");
    fs::write(
        &shim,
        format!(
            "// Auto-generated by host/build.rs.\n\
             pub const PACKAGE_HASH: &str = \"{package_hash}\";\n\
             pub const RUN_HASH: &str = \"{run_hash}\";\n\
             pub type TacboyContext = super::tacit::tacit_p_{package_prefix}_context;\n\
             pub use super::tacit::{run_symbol} as run;\n"
        ),
    )
    .expect("write staged shim");

    println!("cargo:rustc-env=TACIT_BINDINGS_PATH={}", staged.display());
    println!("cargo:rustc-env=TACIT_SHIM_PATH={}", shim.display());
}

fn package_hash_from_lock(path: &Path) -> Option<String> {
    let text = fs::read_to_string(path).ok()?;
    let package_start = text.find("\"package\"")?;
    let after_package = &text[package_start..];
    let deps_start = after_package
        .find("\"dependencies\"")
        .unwrap_or(after_package.len());
    let package_block = &after_package[..deps_start];
    prefixed_hash_value(package_block, "\"hash\"")
}

fn export_hash_from_manifest(path: &Path, alias: &str) -> Option<String> {
    let text = fs::read_to_string(path).ok()?;
    let mut in_exports = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_exports = trimmed == "[exports]";
            continue;
        }
        if !in_exports {
            continue;
        }
        let Some((key, value)) = trimmed.split_once('=') else {
            continue;
        };
        if key.trim() == alias {
            return prefixed_hash_literal(value.trim());
        }
    }
    None
}

fn prefixed_hash_value(text: &str, key: &str) -> Option<String> {
    let key_start = text.find(key)?;
    let after_key = &text[key_start + key.len()..];
    let colon = after_key.find(':')?;
    prefixed_hash_literal(after_key[colon + 1..].trim())
}

fn prefixed_hash_literal(value: &str) -> Option<String> {
    let start = value.find('"')? + 1;
    let rest = &value[start..];
    let end = rest.find('"')?;
    let value = &rest[..end];
    let hash = value.strip_prefix("blake3:")?;
    if hash.len() == 64 && hash.bytes().all(|b| b.is_ascii_hexdigit()) {
        Some(hash.to_string())
    } else {
        None
    }
}

fn hash_prefix(hash: &str) -> &str {
    hash.get(..16).expect("BLAKE3 hash has 16-byte prefix")
}

fn find_host_artifacts(host_dir: &Path) -> Option<(PathBuf, String, PathBuf)> {
    let mut archive: Option<(PathBuf, String)> = None;
    let mut bindings: Option<PathBuf> = None;
    let mut entries: Vec<_> = fs::read_dir(host_dir).ok()?.flatten().collect();
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        if name.starts_with("libtacit_") && name.ends_with(".a") {
            let basename = name
                .trim_start_matches("lib")
                .trim_end_matches(".a")
                .to_string();
            archive = Some((host_dir.to_path_buf(), basename));
        } else if name == "tacit_host.rs" {
            bindings = Some(path);
        }
    }
    if let (Some((dir, base)), Some(b)) = (archive, bindings) {
        Some((dir, base, b))
    } else {
        None
    }
}

fn rerun_if_sources_change(src_dir: &Path) {
    if let Ok(entries) = fs::read_dir(src_dir) {
        for entry in entries.flatten() {
            println!("cargo:rerun-if-changed={}", entry.path().display());
        }
    }
}
